### ISSUE TITLE
When launching pybullet_ros_example.launch  it crashes

### ISSUE THREAD

**Issue by SunnyKatyara** [oscar-lima/pybullet_ros#14]
When i am launching the pybullet_ros_example.launch it returns 

ImportError: No module named 'yaml'
================================================================================REQUIRED process [pybullet_ros-2] has died!
process has died [pid 742, exit code 1, cmd /home/sunny/development/catkinws/src/pybullet_ros/ros/scripts/pybullet_ros_node __name:=pybullet_ros __log:=/home/sunny/.ros/log/a50342f6-1a9f-11ea-81d2-1cb72c397ce2/pybullet_ros-2.log].
log file: /home/sunny/.ros/log/a50342f6-1a9f-11ea-81d2-1cb72c397ce2/pybullet_ros-2*.log
Initiating shutdown!

I am using ROS-Kinetic and ROS-1. What is the issue, can you point out?

Thank You

**Comment by oscar-lima** [comment]
Can you please try:

```
sudo -H pip install pyyaml
```

Then run your launch file again.
