### ISSUE TITLE
ROS Publisher for Depth Images and Pointclouds

### ISSUE THREAD

**Issue by QingkaiLu** [oscar-lima/pybullet_ros#15]
This pybullet_bridge seems to be quite useful for people who want to use ROS and pybullet together. Will you consider to add ros publishers for camera info, depth images, and point clouds in the future? Thanks.

**Comment by oscar-lima** [comment]
That would definitely be great! , yes it is planned. Not sure when I will have the time to do it though, maybe someone can help?

**Comment by oscar-lima** [comment]
update: publishing pcl could be done using: https://github.com/bulletphysics/bullet3/issues/1924#issuecomment-1091876325 in https://github.com/oscar-lima/pybullet_ros/blob/noetic/ros/src/pybullet_ros/plugins/rgbd_camera.py

**Comment by oscar-lima** [comment]
seems the issue is repeated, see: https://github.com/oscar-lima/pybullet_ros/issues/3
