### ISSUE TITLE
Does pybullet_ros work on plain ros-melodic distribution?

### ISSUE THREAD

**Issue by b4be1** [oscar-lima/pybullet_ros#16]
This is a `python3` package. I am getting errors when running example code because `rospy` is imported from `python2.7`. Do I need to build `ros-melodic` with `python3` support to use `pybullet_ros`?

**Comment by And1210** [comment]
I am running pybullet_ros with melodic (no python errors). I have python3 installed on my system alongside python 2.7 for melodic so maybe you need to install python3? I installed the anaconda package which comes with python3.

**Comment by b4be1** [comment]
Somehow for me it didn't work with Anaconda python. Reinstalling ros-melodic and using system python3 made it work. Thanks for the feedback.
