### ISSUE TITLE
very new to this and I'm getting this error but I'm not sure what the issue might be 

### ISSUE THREAD

**Issue by oknaomi** [oscar-lima/pybullet_ros#18]
import pybullet_ros.pybullet_ros
ImportError: No module named 'pybullet_ros'
================================================================================REQUIRED process [pybullet_ros-2] has died!
process has died [pid 12922, exit code 1, cmd /home/naomi/catkin_wsROSPY/src/pybullet_ros/ros/scripts/pybullet_ros_node __name:=pybullet_ros __log:=/home/naomi/.ros/log/3c765640-caaa-11ea-9f68-1094bbd00390/pybullet_ros-2.log].
log file: /home/naomi/.ros/log/3c765640-caaa-11ea-9f68-1094bbd00390/pybullet_ros-2*.log
Initiating shutdown!

**Comment by oscar-lima** [comment]
after creating a catkin workspace, cloning this repo, building (catkin build) and sourcing workspace (source ~/my_catkin_ws/setup.bash) the module should resolve properly
