### ISSUE TITLE
Integration with ROS Navigation stack

### ISSUE THREAD

**Issue by oscar-lima** [oscar-lima/pybullet_ros#6]
Configure ROS move base with at least one robot as an example that this wrapper is fully functional and compatible with the ROS standard packages

**Comment by oscar-lima** [comment]
The following is done:

- subscription to /cmd_vel
- publication of transform /odom -> /base_link
- lidar plugin

Missing:
- Configuration launch files

**Comment by amjack0** [comment]
Hi everyone,
Is there any update on this topic ?

**Comment by oscar-lima** [comment]
Not to my knowledge, collaboration here would be great!

**Comment by VismayVakharia** [comment]
I tried using this repository with a simple robot and connected it with ROS Noetic navigation stack. It seems to be working fine.

**Comment by oscar-lima** [comment]
Nice! thank you. I will close it then for now, if someone experiences issues around it feel free to re-open
